<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MCAL</AssemblyName>
    <RootNamespace>MCAL</RootNamespace>
    <Product>Multi Channel Audio Leveler</Product>
    <AssemblyTitle>MCAL - Multi Channel Audio Leveler</AssemblyTitle>
    <Company>rosscarlson</Company>
    <Version>0.4.0</Version>
    <ApplicationIcon>Assets\MCAL.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\MCAL.ico" />
  </ItemGroup>

</Project>
